const cocktails = [
            {
            idDrink: "15997",
			nameDrink: "GG",
			dkCategory: "Ordinary Drink",
			dkAlcoholic: "Optional alcohol",
			dkGlass: "Collins Glass",
            dkInstructions: "Pour the Galliano liqueur over ice. Fill the remainder of the glass with ginger ale and thats all there is to it. You now have a your very own GG.",
            dkDrinkThumb: "https:\/\/www.thecocktaildb.com\/images\/media\/drink\/vyxwut1468875960.jpg",
            dkIngredient1: "Galliano",
			dkIngredient2: "Ginger ale",
			dkIngredient3: "Ice"
            },
            {
            idDrink: "17222",
            nameDrink: "A1",
            dkCategory: "Cocktail",
            dkAlcoholic: "Alcoholic",
            dkGlass: "Cocktail Glass",
            dkInstructions: "Pour all ingredients into a cocktail shaker, mix and serve over ice into a chilled glass",
            dkDrinkThumb: "https:\/\/www.thecocktaildb.com\/images\/media\/drink\/2x8thr1504816928.jpg",
            dkIngredient1: "Gin",
            dkIngredient2: "Grand Marnier",
            dkIngredient3: "Lemon Juice",
            dkIngredient4: "Grenadine"
            },
            {
            idDrink: "13501",
            nameDrink: "ABC",
            dkCategory: "Shot",
            dkAlcoholic: "Alcoholic",
            dkGlass: "Shot Glass",
            dkInstructions: "Layered in a shot glass.",
            dkDrinkThumb: "https:\/\/www.thecocktaildb.com\/images\/media\/drink\/tqpvqp1472668328.jpg",
            dkIngredient1: "Amaretto",
            dkIngredient2: "Baileys irish cream",
            dkIngredient3: "Cognac",
            },
            {
            idDrink: "17203",
            nameDrink: "Kir",
            dkCategory: "Ordinary Drink",
            dkAlcoholic: "Alcoholic",
            dkGlass: "Wine Glass",
            dkInstructions: "Add the crème de cassis to the bottom of the glass, then top up with wine.",
            dkDrinkThumb: "https:\/\/www.thecocktaildb.com\/images\/media\/drink\/apneom1504370294.jpg",
            dkIngredient1: "Creme de Cassis",
            dkIngredient2: "Champagne",
            },
            {
            idDrink: "14229",
            nameDrink: "747",
            dkCategory: "Shot",
            dkAlcoholic: "Alcoholic",
            dkGlass: "Shot Glass",
            dkInstructions: "Pour Kaluha, then Baileys, then Frangelico not chilled and not layered -- SERVE!!!",
            dkDrinkThumb: "https:\/\/www.thecocktaildb.com\/images\/media\/drink\/xxsxqy1472668106.jpg",
            dkIngredient1: "Kahlua",
            dkIngredient2: "Baileys irish cream",
            dkIngredient3: "Frangelico",
            },  
            {  
            idDrink: "15288",
            nameDrink: "252",
            dkCategory: "Shot",
            dkAlcoholic: "Alcoholic",
            dkGlass: "Shot Glass",
            dkInstructions: "Add both ingredients to shot glass, shoot, and get drunk quick.",
            dkDrinkThumb: "https:\/\/www.thecocktaildb.com\/images\/media\/drink\/rtpxqw1468877562.jpg",
            dkIngredient1: "151 proof rum",
            dkIngredient2: "Wild Turkey",
            }, 
            { 
            idDrink: "17225",
            nameDrink: "Ace",
            dkCategory: "Cocktail",
            dkAlcoholic: "Alcoholic",
            dkGlass: "Martini Glass",
            dkInstructions: "Shake all the ingredients in a cocktail shaker and ice then strain in a cold glass.",
            dkDrinkThumb: "https:\/\/www.thecocktaildb.com\/images\/media\/drink\/l3cd7f1504818306.jpg",
            dkIngredient1: "Gin",
            dkIngredient2: "Grenadine",
            dkIngredient3: "Heavy cream",
            dkIngredient4: "Milk",
			dkIngredient5: "Egg White"
            },
            {
            idDrink: "13332",
            nameDrink: "B-53",
            dkCategory: "Shot",
            dkAlcoholic: "Alcoholic",
            dkGlass: "Collins Glass",
            dkInstructions: "Layer the Kahlua, Sambucca and Grand Marnier into a shot glas in that order. Better than B-52.",
            dkIngredient1: "Kahlua",
            dkIngredient2: "Sambuca",
            dkIngredient3: "Grand Marnier",
            },  
            {  
            idDrink: "12093",
            nameDrink: "Rum Sour",
            dkCategory: "Ordinary Drink",
            dkAlcoholic: "Alcoholic",
            dkGlass: "Whiskey Sour Glass",
            dkInstructions: "In a shaker half-filled with ice cubes, combine the rum, lemon juice, and sugar. Shake well. Strain into a sour glass and garnish with the orange slice and the cherry.",
            dkDrinkThumb: "https:\/\/www.thecocktaildb.com\/images\/media\/drink\/bylfi21504886323.jpg",
            dkIngredient1: "Light rum",
            dkIngredient2: "Lemon juice",
            dkIngredient3: "Sugar",
            dkIngredient2: "Orange",
            dkIngredient3: "Maraschino cherry",
            },
            {
            idDrink: "12097",
            nameDrink: "Rum Toddy",
            dkCategory: "Ordinary Drink",
            dkAlcoholic: "Alcoholic",
            dkGlass: "Old-Fashion Glass",
            dkInstructions: "Dissolve powdered sugar in water in an old-fashioned glass. Add rum and one ice cube and stir. Add the twist of lemon peel and serve.",
            dkDrinkThumb: "https:\/\/www.thecocktaildb.com\/images\/media\/drink\/athdk71504886286.jpg",
            dkIngredient1: "Rum",
            dkIngredient2: "Powdered sugar",
            dkIngredient3: "Lemon peel",
            dkIngredient2: "Water",
            },
            {
            idDrink: "16250",
            nameDrink: "Rum Runner",
            dkCategory: "Punch Party Drink",
            dkAlcoholic: "Alcoholic",
            dkGlass: "Cocktail Glass",
            dkInstructions: "Mix all ingredients in glass & add ice.",
            dkDrinkThumb: "https:\/\/www.thecocktaildb.com\/images\/media\/drink\/vqws6t1504888857.jpg",
            dkIngredient1: "Mailbu rum",
            dkIngredient2: "Blackberry brandy",
            dkIngredient3: "Orange juice",
            dkIngredient2: "Pineapple juice",
            dkIngredient2: "Cranberry juice",
            },
            {
            idDrink: "12089",
            nameDrink: "Rum Old-Fashioned",
            dkCategory: "Ordinary Drink",
            dkAlcoholic: "Alcoholic",
            dkGlass: "Old-Fashioned Glass",
            dkInstructions: "Stir powdered sugar, water, and bitters in an old-fashioned glass. When sugar has dissolved add ice cubes and light rum. Add the twist of lime peel, float 151 proof rum on top, and serve.",
            dkDrinkThumb: "https:\/\/www.thecocktaildb.com\/images\/media\/drink\/otn2011504820649.jpg",
            dkIngredient1: "Light rum",
            dkIngredient2: "151 proof rum",
            dkIngredient3: "Powdered sugar",
            dkIngredient2: "Bitters",
            dkIngredient2: "Water",
            dkIngredient2: "Lime peel",
            },
            {
            idDrink: "11004",
            nameDrink: "Whiskey Sour",
            dkCategory: "Ordinary Drink",
            dkAlcoholic: "Alcoholic",
            dkGlass: "Old-Fashioned Glass",
            dkInstructions: "Shake with ice. Strain into chilled glass, garnish and serve. If served 'On the rocks', strain ingredients into old-fashioned glass filled with ice.",
            dkDrinkThumb: "https:\/\/www.thecocktaildb.com\/images\/media\/drink\/hbkfsh1589574990.jpg",
            dkIngredient1: "Blended whiskey",
            dkIngredient2: "Lemon",
            dkIngredient3: "Powdered sugar",
            dkIngredient2: "Cherry",
            dkIngredient2: "Lemon",
            },
            {
            idDrink: "11007",
            nameDrink: "Margarita",
            dkCategory: "Ordinary Drink",
            dkAlcoholic: "Alcoholic",
            dkGlass: "Cocktail Glass",
            dkInstructions: "Rub the rim of the glass with the lime slice to make the salt stick to it. Take care to moisten only the outer rim and sprinkle the salt on it. The salt should present to the lips of the imbiber and never mix into the cocktail. Shake the other ingredients with ice, then carefully pour into the glass.",
            dkDrinkThumb: "https:\/\/www.thecocktaildb.com\/images\/media\/drink\/5noda61589575158.jpg",
            dkIngredient1: "Tequila",
            dkIngredient2: "Triple sec",
            dkIngredient3: "Lime juice",
            dkIngredient2: "Salt",
            },
        ]




module.exports = cocktails
